"""SovereignOps ingest helpers."""

from .checksum import (
    ChecksumIndex,
    DeduplicationResult,
    checksum_bytes,
    checksum_text,
    deduplicate_texts,
    duplicate_checksums,
)
from .citation import Citation, CitationRange
from .connectors import (
    CSVConnector,
    ConnectorError,
    CsvParseResult,
    CsvValidationError,
    IngestChunk,
    JSONConnector,
    MarkdownConnector,
    parse_csv,
    parse_json,
    parse_markdown,
)
from .pipeline import IngestItem, IngestResult, normalize_item
from .structured import (
    CSVStructuredConnector,
    JSONStructuredConnector,
    LocalDataSafetyFinding,
    MarkdownStructuredConnector,
    StructuredDocument,
    StructuredImportResult,
    StructuredValidationError,
    import_csv,
    import_json,
    import_markdown,
)

__all__ = [
    "CSVConnector",
    "ChecksumIndex",
    "Citation",
    "CitationRange",
    "ConnectorError",
    "CsvParseResult",
    "CsvValidationError",
    "DeduplicationResult",
    "IngestChunk",
    "IngestItem",
    "IngestResult",
    "JSONConnector",
    "MarkdownConnector",
    "CSVStructuredConnector",
    "JSONStructuredConnector",
    "LocalDataSafetyFinding",
    "MarkdownStructuredConnector",
    "StructuredDocument",
    "StructuredImportResult",
    "StructuredValidationError",
    "checksum_bytes",
    "checksum_text",
    "deduplicate_texts",
    "duplicate_checksums",
    "import_csv",
    "import_json",
    "import_markdown",
    "normalize_item",
    "parse_csv",
    "parse_json",
    "parse_markdown",
]
