"""SovereignOps ingest helpers."""

from .checksum import (
    ChecksumIndex,
    DeduplicationResult,
    checksum_bytes,
    checksum_text,
    deduplicate_texts,
    duplicate_checksums,
)
from .citation import Citation, CitationRange
from .connectors import (
    CSVConnector,
    ConnectorError,
    CsvParseResult,
    CsvValidationError,
    IngestChunk,
    JSONConnector,
    MarkdownConnector,
    parse_csv,
    parse_json,
    parse_markdown,
)
from .index import (
    IndexAddResult,
    IndexDocument,
    SearchIndex,
    SearchQuery,
    SearchResult,
)
from .logs import (
    JSONLLogConnector,
    LogEvent,
    LogImportResult,
    PlainTextLogConnector,
    parse_jsonl_logs,
    parse_plain_text_logs,
)
from .pipeline import IngestItem, IngestResult, normalize_item
from .quarantine import (
    QuarantineCase,
    QuarantineDecision,
    QuarantineError,
    QuarantineTransitionError,
    build_quarantine_case,
    build_quarantine_cases,
    redacted_preview_text,
    reject_case,
    release_case,
)
from .repository import (
    RepositoryConnector,
    RepositoryConnectorError,
    RepositoryRecord,
    detect_media_type,
    is_path_inside_root,
    is_text_like_media_type,
    scan_repository,
)
from .structured import (
    CSVStructuredConnector,
    JSONStructuredConnector,
    LocalDataSafetyFinding,
    MarkdownStructuredConnector,
    StructuredDocument,
    StructuredImportResult,
    StructuredValidationError,
    import_csv,
    import_json,
    import_markdown,
)

__all__ = [
    "CSVConnector",
    "ChecksumIndex",
    "Citation",
    "CitationRange",
    "ConnectorError",
    "CsvParseResult",
    "CsvValidationError",
    "DeduplicationResult",
    "IngestChunk",
    "IngestItem",
    "IngestResult",
    "IndexAddResult",
    "IndexDocument",
    "JSONLLogConnector",
    "JSONConnector",
    "MarkdownConnector",
    "LogEvent",
    "LogImportResult",
    "CSVStructuredConnector",
    "JSONStructuredConnector",
    "LocalDataSafetyFinding",
    "MarkdownStructuredConnector",
    "PlainTextLogConnector",
    "QuarantineCase",
    "QuarantineDecision",
    "QuarantineError",
    "QuarantineTransitionError",
    "RepositoryConnector",
    "RepositoryConnectorError",
    "RepositoryRecord",
    "SearchIndex",
    "SearchQuery",
    "SearchResult",
    "build_quarantine_case",
    "build_quarantine_cases",
    "StructuredDocument",
    "StructuredImportResult",
    "StructuredValidationError",
    "checksum_bytes",
    "checksum_text",
    "deduplicate_texts",
    "detect_media_type",
    "duplicate_checksums",
    "import_csv",
    "import_json",
    "import_markdown",
    "is_path_inside_root",
    "is_text_like_media_type",
    "normalize_item",
    "parse_csv",
    "parse_json",
    "parse_jsonl_logs",
    "parse_markdown",
    "parse_plain_text_logs",
    "redacted_preview_text",
    "reject_case",
    "release_case",
    "scan_repository",
]
